# Generated by Django 4.2.1 on 2024-09-26 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('generator', '0005_collectible_scorecategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGameplay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generator.question')),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generator.quest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_gameplay',
                'unique_together': {('user', 'quest')},
            },
        ),
        migrations.CreateModel(
            name='UserScoreByCategoryForGameplay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('score_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generator.scorecategory')),
                ('user_gameplay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_interface.usergameplay')),
            ],
        ),
    ]
