# Generated by Django 4.2.1 on 2024-10-02 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('generator', '0007_quest_max_questions_universe_main_characters'),
        ('game_interface', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCollectible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('collectible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generator.collectible')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collectibles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'collectible')},
            },
        ),
    ]
