# Generated by Django 4.2.1 on 2024-11-10 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_interface', '0003_useruniversesuggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='useruniversesuggestion',
            name='email',
            field=models.TextField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='useruniversesuggestion',
            name='name',
            field=models.TextField(null=True, unique=True),
        ),
    ]
