# Generated by Django 4.2.1 on 2024-11-10 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_interface', '0004_useruniversesuggestion_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useruniversesuggestion',
            name='email',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='useruniversesuggestion',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
