# Generated by Django 4.2.1 on 2024-11-10 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_interface', '0005_alter_useruniversesuggestion_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useruniversesuggestion',
            name='universe_description',
            field=models.CharField(max_length=1500),
        ),
    ]
