# Generated by Django 4.2.1 on 2024-11-14 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_interface', '0006_alter_useruniversesuggestion_universe_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='useruniversesuggestion',
            name='mobile',
            field=models.TextField(blank=True, null=True),
        ),
    ]
