# Generated by Django 4.2.1 on 2024-09-23 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='main_characters',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='quest',
            name='story_outline',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='universe',
            name='key_elements',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='question',
            name='audio_file_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='image_file_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
