# Generated by Django 4.2.1 on 2024-09-24 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('generator', '0002_quest_main_characters_quest_story_outline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='collectible_reward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.collectible'),
        ),
        migrations.AddField(
            model_name='option',
            name='score_rewards',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='quest',
            name='min_score_requirement',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='QuestScoreCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_score', models.IntegerField()),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generator.quest')),
                ('score_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.scorecategory')),
            ],
        ),
        migrations.CreateModel(
            name='QuestCollectible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rarity', models.FloatField(default=0.1)),
                ('collectible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.collectible')),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generator.quest')),
            ],
        ),
        migrations.AddField(
            model_name='quest',
            name='collectibles',
            field=models.ManyToManyField(through='generator.QuestCollectible', to='user.collectible'),
        ),
        migrations.AddField(
            model_name='quest',
            name='score_categories',
            field=models.ManyToManyField(through='generator.QuestScoreCategory', to='user.scorecategory'),
        ),
    ]
