# Generated by Django 4.2.1 on 2024-09-26 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0003_option_collectible_reward_option_score_rewards_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='characters',
            field=models.JSONField(default=list),
        ),
    ]
