# Generated by Django 4.2.1 on 2024-09-26 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0004_question_characters'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collectible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image_path', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ScoreCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('icon', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='questscorecategory',
            name='quest',
        ),
        migrations.RemoveField(
            model_name='questscorecategory',
            name='score_category',
        ),
        migrations.RemoveField(
            model_name='option',
            name='collectible_reward',
        ),
        migrations.RemoveField(
            model_name='quest',
            name='collectibles',
        ),
        migrations.RemoveField(
            model_name='quest',
            name='score_categories',
        ),
        migrations.DeleteModel(
            name='QuestCollectible',
        ),
        migrations.DeleteModel(
            name='QuestScoreCategory',
        ),
        migrations.AddField(
            model_name='scorecategory',
            name='quest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generator.quest'),
        ),
        migrations.AddField(
            model_name='collectible',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generator.option'),
        ),
    ]
