# Generated by Django 4.2.1 on 2024-09-30 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0005_collectible_scorecategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='audio_url',
            field=models.CharField(blank=True, help_text='Each quest can have an audio file associated with it. This audio will be played when the quest is being played.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='quest',
            name='thumbnail',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='universe',
            name='thumbnail',
            field=models.URLField(blank=True, null=True),
        ),
    ]
