# Generated by Django 4.2.1 on 2024-10-01 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0006_quest_audio_url_quest_thumbnail_universe_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='max_questions',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='universe',
            name='main_characters',
            field=models.JSONField(default=list),
        ),
    ]
