# Generated by Django 4.2.1 on 2024-10-02 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0007_quest_max_questions_universe_main_characters'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='parent_option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_questions', to='generator.option'),
        ),
    ]
