# Generated by Django 4.2.1 on 2024-10-21 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0009_question_question_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='slug',
            field=models.SlugField(default='test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='universe',
            name='slug',
            field=models.SlugField(default='test'),
            preserve_default=False,
        ),
    ]
