# Generated by Django 4.2.1 on 2024-10-21 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0010_quest_slug_universe_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='universe',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
