# Generated by Django 4.2.1 on 2024-10-21 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0011_alter_quest_slug_alter_universe_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='universe',
            name='meta',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='universe',
            name='narrator_voice_description',
            field=models.TextField(blank=True, help_text='An old American male voice with a slight hoarseness in his throat. Perfect for news', null=True),
        ),
        migrations.AddField(
            model_name='universe',
            name='narrator_voice_samples',
            field=models.JSONField(default=list),
        ),
    ]
