# Generated by Django 4.2.1 on 2024-10-23 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0014_questgameplayimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectible',
            name='image_path',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='option',
            name='reward_image_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='quest',
            name='audio_url',
            field=models.CharField(blank=True, help_text='Each quest can have an audio file associated with it. This audio will be played when the quest is being played.', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='questgameplayimages',
            name='image_path',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='question',
            name='audio_file_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='image_file_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='questrewardcollection',
            name='image_path',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='scorecategory',
            name='icon',
            field=models.CharField(max_length=500),
        ),
    ]
