# Generated by Django 4.2.1 on 2024-10-24 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0015_alter_collectible_image_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='background_audio_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
