# Generated by Django 4.2.1 on 2024-11-07 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0017_character'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, default='', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, default='', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('type', models.CharField(choices=[('QUEST', 'Quest'), ('TRIVIA', 'Trivia'), ('AUDIO_STORY', 'Audio Story'), ('COMIC', 'Comic'), ('OTHERS', 'Others')], default='OTHERS', max_length=50)),
                ('display_order', models.IntegerField(blank=True, default=1, help_text='Order of components in HomePage (ascending)', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trivia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, default='', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TriviaQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField(blank=True, null=True)),
                ('question_text', models.TextField()),
                ('options', models.JSONField()),
                ('image', models.URLField(blank=True, null=True)),
                ('next_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_questions_set', to='generator.triviaquestion')),
                ('previous_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_questions_set', to='generator.triviaquestion')),
                ('trivia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generator.trivia')),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('episode_number', models.IntegerField(blank=True, null=True)),
                ('audio_file_path', models.CharField(max_length=500)),
                ('image', models.URLField(blank=True, null=True)),
                ('audio_story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generator.audiostory')),
                ('next_episode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_episodes_from', to='generator.episode')),
                ('previous_episode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_episodes_from', to='generator.episode')),
            ],
        ),
        migrations.CreateModel(
            name='ComicPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.IntegerField(blank=True, null=True)),
                ('image', models.URLField(blank=True, null=True)),
                ('comic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generator.comic')),
                ('next_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_page_set', to='generator.comicpage')),
                ('previous_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_page_set', to='generator.comicpage')),
            ],
        ),
    ]
