# Generated by Django 4.2.1 on 2024-11-07 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0018_audiostory_comic_homepage_trivia_triviaquestion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiostory',
            name='thumbnail',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='comic',
            name='thumbnail',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='comicpage',
            name='image',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='audio_file_path',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='episode',
            name='image',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='thumbnail',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='trivia',
            name='thumbnail',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='triviaquestion',
            name='image',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
