# Generated by Django 4.2.1 on 2024-11-07 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0019_alter_audiostory_thumbnail_alter_comic_thumbnail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comicpage',
            name='narration_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
