# Generated by Django 4.2.1 on 2024-11-09 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0021_audiostory_deleted_at_character_deleted_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortVideos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('thumbnail', models.URLField(blank=True, max_length=1000, null=True)),
                ('url', models.URLField(max_length=1000)),
                ('slug', models.SlugField(blank=True, default='', unique=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
