# Generated by Django 4.2.1 on 2024-11-09 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0022_shortvideos'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='intro',
            field=models.TextField(default='intro to quest'),
            preserve_default=False,
        ),
    ]
