# Generated by Django 4.2.1 on 2024-11-10 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0023_quest_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='trivia',
            name='audio_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
