# Generated by Django 4.2.1 on 2024-11-11 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0024_trivia_audio_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
