# Generated by Django 4.2.1 on 2024-11-11 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0025_homepage_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='show_in_banner',
            field=models.BooleanField(default=False),
        ),
    ]
