# Generated by Django 4.2.1 on 2024-11-11 15:30

from django.db import migrations
import utils.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0026_homepage_show_in_banner'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='audiostory',
            managers=[
                ('objects', utils.helpers.BaseManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='character',
            managers=[
                ('objects', utils.helpers.BaseManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='collectible',
            managers=[
                ('objects', utils.helpers.BaseManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='comic',
            managers=[
                ('objects', utils.helpers.BaseManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='comicpage',
            managers=[
                ('objects', utils.helpers.BaseManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='episode',
            managers=[
                ('objects', utils.helpers.BaseManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='homepage',
            managers=[
                ('objects', utils.helpers.BaseManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='option',
            managers=[
                ('objects', utils.helpers.BaseManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='quest',
            managers=[
                ('objects', utils.helpers.BaseManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='questgameplayimages',
            managers=[
                ('objects', utils.helpers.BaseManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='question',
            managers=[
                ('objects', utils.helpers.BaseManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='questrewardcollection',
            managers=[
                ('objects', utils.helpers.BaseManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='scorecategory',
            managers=[
                ('objects', utils.helpers.BaseManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='shortvideos',
            managers=[
                ('objects', utils.helpers.BaseManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='trivia',
            managers=[
                ('objects', utils.helpers.BaseManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='triviaquestion',
            managers=[
                ('objects', utils.helpers.BaseManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='universe',
            managers=[
                ('objects', utils.helpers.BaseManager()),
            ],
        ),
    ]
