# Generated by Django 4.2.1 on 2024-11-15 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0027_alter_audiostory_managers_alter_character_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortvideos',
            name='raw_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
