# Generated by Django 4.2.1 on 2024-11-18 11:32

from django.db import migrations, models
import utils.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0027_alter_audiostory_managers_alter_character_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Mystery & Crime', 'Mystery Crime'), ('Tech Innovations', 'Tech Innovations'), ('Historical Events', 'Historical Events'), ('Environmental Awareness', 'Environmental Awareness'), ('Cultural Traditions', 'Cultural Traditions'), ('Health & Wellness', 'Health Wellness'), ('Art Movements', 'Art Movements'), ('Science Discoveries', 'Science Discoveries'), ('Entrepreneurship & Startups', 'Entrepreneurship Startups'), ('Political', 'Political'), ('Sports', 'Sports'), ('War', 'War'), ('Celebrities', 'Celebrities'), ('Others', 'Others')], default='Others', max_length=50)),
                ('description', models.TextField()),
                ('thumbnail', models.URLField(blank=True, max_length=1000, null=True)),
                ('audio_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('video_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('slug', models.SlugField(blank=True, default='', unique=True)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', utils.helpers.BaseManager()),
            ],
        ),
    ]
