# Generated by Django 4.2.1 on 2024-11-18 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0028_news'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='type',
            new_name='category',
        ),
    ]
