# Generated by Django 4.2.1 on 2024-11-23 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0029_rename_type_news_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('Mystery & Crime', 'Mystery Crime'), ('Tech Innovations', 'Tech Innovations'), ('Historical Events', 'Historical Events'), ('Environmental Awareness', 'Environmental Awareness'), ('Cultural Traditions', 'Cultural Traditions'), ('Health & Wellness', 'Health Wellness'), ('Art Movements', 'Art Movements'), ('Science Discoveries', 'Science Discoveries'), ('Entrepreneurship & Startups', 'Entrepreneurship Startups'), ('Political', 'Political'), ('Sports', 'Sports'), ('War', 'War'), ('Celebrities', 'Celebrities'), ('Others', 'Others')], default='Others', max_length=100),
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
