# Generated by Django 4.2.1 on 2024-11-23 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0030_alter_news_category_alter_news_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=100, unique=True),
        ),
    ]
