# Generated by Django 4.2.1 on 2024-12-04 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0028_shortvideos_raw_url'),
        ('generator', '0031_alter_news_slug'),
    ]

    operations = [
    ]
