# Generated by Django 4.2.1 on 2024-09-26 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0005_collectible_scorecategory_and_more'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercollectible',
            name='collectible',
        ),
        migrations.RemoveField(
            model_name='usercollectible',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userscore',
            name='category',
        ),
        migrations.RemoveField(
            model_name='userscore',
            name='user',
        ),
        migrations.DeleteModel(
            name='Collectible',
        ),
        migrations.DeleteModel(
            name='ScoreCategory',
        ),
        migrations.DeleteModel(
            name='UserCollectible',
        ),
        migrations.DeleteModel(
            name='UserScore',
        ),
    ]
