# Generated by Django 4.2.1 on 2024-12-17 12:21

import common.helpers
import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_userprofile_gpt_thread_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('meta', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
                ('user_id', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('prev_state', models.JSONField(default=dict)),
                ('new_state', models.JSONField(default=dict)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', common.helpers.BaseManager()),
            ],
        ),
    ]
