# Generated by Django 4.2.1 on 2024-12-20 11:09

import common.helpers
import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_logtable_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('meta', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
                ('user_id', models.IntegerField(null=True)),
                ('content_id', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'content_recommendations',
            },
            managers=[
                ('objects', common.helpers.BaseManager()),
            ],
        ),
    ]
